---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
      - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
exclude_paths:
- public/
